### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by manwaring** [thundra-io/thundra-vscode-issues#1]
Tried the plugin this afternoon and love it!  Are there are any plans to support TypeScript as a runtime in the future?

**Comment by BjMrq** [comment]
WOuld be very nice!

**Comment by s1mrankaur** [comment]
support this

**Comment by rwxdash** [comment]
Sorry that this issue was overlooked.

We already support debugging TypeScript and/or bundles. However, it just needs a bit more configuration on your end. We have a (small) section in our [documentation](https://apm.docs.thundra.io/node.js/online-debugging#using-the-aws-lambda-debugging-debugging-with-typescript) for debugging with TypeScript. Although, some steps like `rootDir` changes might not be necessary for everyone. We're planning to update and expand the documentation for this.

The important part is that you have your source maps deployed with your function as well as having them build on your local. Then, for the VSCode plugin, change your local root to your build folder using the [Change Local Root Command](https://apm.docs.thundra.io/ide-integrations/vscode-plugin/changing-local-root).

The idea here is to match the folder structure to your remote. So, set your local root accordingly.

If you are still having problems with TypeScript, we can welcome you to our [Slack community](https://www.thundra.io/thundra-slack-invitation?hsLang=en) channel.
